#!/bin/sh

__msg() {
    echo "$*"
}
_msg() {
    ! (echo "$quiet" | grep -q -E "[Yy1]") && __msg "$*"
}
fatal() {
    __msg "[F] $*"
    sleep 5
    exit 1
}
error() {
    __msg "[E] $*"
    sleep 5
}
warn() {
    _msg "[W] $*"
}
info() {
    _msg "[I] $*"
}

load_cmdline_to_vars() {
    TEMPFILE=$(mktemp)
    #load linux vars
    #needed mainly for root

    #The extra space will make sure that read does not fail at the last param
    { cat "$1"; echo -ne " "; } | while read -r -d " " p; do
            [ -z "$p" ] && continue
            echo -ne "$p" | grep -q "\."
            [ $? -eq 0 ] && continue
            echo "export \"$p\"" >> "$TEMPFILE"
    done
    . "$TEMPFILE"
    rm -f "$TEMPFILE"
}

__resolve_uuid_to_block() {
    #Get the uuid
    UUID="$1"

    #BLKSUUIDS=$(blkid | sed -n 's/\/dev\/\(.*\): .*UUID=\"\([^\"]*\)\".*/\1|\2/p')
    BLKSUUIDS=$(blkid | sed -n 's/\(.*\): .*UUID=\"\([^\"]*\)\".*/\1|\2/p')
    echo "$BLKSUUIDS" | while read -r p || [ -n "$p" ]; do
        BLKPATH=$(echo -ne "$BLKSUUIDS" | cut -d "|" -f 1)
        BLKUUID=$(echo -ne "$BLKSUUIDS" | cut -d "|" -f 2)
        if [ "$BLKUUID" = "$UUID" ]; then
            echo -ne "$BLKPATH"
            #return 0
        fi
    done

    #return 1
}

__wait_and_mount() {
    ROOT="$1"
    MNTPOINT="$2"
    MAXCOUNT=$3

    COUNT=0

    echo "$ROOT" | grep -iq "UUID="
    [ $? -eq 0 ] && info "UUID detected, will try to resolve to block"

    while true; do
        #TODO: Maybe check for PART UUID
        echo "$ROOT" | grep -iq "UUID="
        if [ $? -eq 0 ]; then
            UUID=$(echo -ne "$ROOT" | sed -e s/^[Uu][Uu][Ii][Dd]=//)

            NEWROOT=$(__resolve_uuid_to_block "$UUID")
            if [ -z "$NEWROOT" ]; then
                warn "Unable to resolve UUID $UUID"
            else
                info "Resolved $UUID to $NEWROOT"
                ROOT="$NEWROOT"
            fi
        fi

        mount -o ro "$ROOT" "$MNTPOINT"
        RET=$?
        if [ "$RET" -ne 0 ] && [ $COUNT -lt $MAXCOUNT ]; then
            info "Waiting for $ROOT ..."
            sleep 10
            COUNT=$((COUNT + 1))
            continue
        fi
        [ "$RET" -eq 0 ] && break

        return 1
    done

    return 0
}

__try_to_extract_cpio() {
    FILE="$1"
    OUT="$2"

    TYPE=$(file -b --mime-type "$FILE" | cut -d ";" -f1 | tr '[:upper:]' '[:lower:]')
    if [ "$TYPE" = "application/zstd" ]; then
        zstd -dc "$FILE" | cpio -idm --no-preserve-owner -D "$OUT"
    elif [ "$TYPE" = "application/x-xz" ]; then
        xz -dc "$FILE" | cpio -idm --no-preserve-owner -D "$OUT"
    elif [ "$TYPE" = "application/gzip" ]; then
        gzip -dc "$FILE" | cpio -idm --no-preserve-owner -D "$OUT"
    elif [ "$TYPE" = "application/x-cpio" ]; then
        cat "$FILE" | cpio -idm --no-preserve-owner -D "$OUT"
    else
        error "Unknown init format: $TYPE, output from file: $(file $FILE)"
        return 1
    fi

    return 0
}
