#!/bin/sh

MOUNTPOINT="/mnt"

. /functions

#mount the mounts
/bin/mount -t proc proc /proc
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t sysfs sysfs /sys
/bin/mount -o remount,rw /

# Load Linux cmdline to variables
load_cmdline_to_vars "/proc/cmdline"

#try to mount root
[ -z "${root}" ] && fatal "root is not found or zero!"

! __wait_and_mount "${root}" "$MOUNTPOINT" 3 && fatal "Unable to mount root!"

#Check the menu
[ ! -f "$MOUNTPOINT/boot/menu.conf" ] && fatal "/boot/menu.conf is NOT found!"

#Run the menu selector
cd /menu
python3 ./process_menu.py "$MOUNTPOINT/boot/menu.conf" 2>/tmp/menu_output
[ $? -ne 0 ] && fatal "Menu selector returned NON-zero!!!!"

cd /

#Process the selected item...
NAME=$(cat /tmp/menu_output | cut -d "|" -f 1)
FILEPATH=$(cat /tmp/menu_output | cut -d "|" -f 2 | sed -e 's/^\///')
FILENAME=$(basename "$FILEPATH")
#VARS=$(cat /tmp/menu_output | cut -d "|" -f 3-)
[ ! -z `cat /tmp/menu_output | cut -d "|" -f 3-` ] && (cat /tmp/menu_output | cut -d "|" -f 3- | tr "|" "\n" | sed -e 's/^/export /' > /tmp/item_VARS)

[ ! -f "$MOUNTPOINT/$FILEPATH" ] && fatal "Booting file $FILEPATH is NOT found!!!!"

cp "$MOUNTPOINT/$FILEPATH" "/tmp/$FILENAME"

umount "$MOUNTPOINT"
mount -t tmpfs tmpfs "$MOUNTPOINT"

echo "Booting $NAME..."

! __try_to_extract_cpio "/tmp/$FILENAME" "$MOUNTPOINT" && fatal "Unable to extract the init cpio archive"

#Try to detect the init location
if [ -z "$INIT" ]; then
    [ -e "/mnt/bin/sh" ] && INIT="/bin/sh"
    [ -e "/mnt/bin/init" ] && INIT="/bin/init"
    [ -e "/mnt/etc/init" ] && INIT="/etc/init"
    [ -e "/mnt/sbin/init" ] && INIT="/sbin/init"
    [ -e "/mnt/init" ] && INIT="/init"
    [ ! -z "$rdinit" ] && INIT="$rdinit"
fi
if [ -z "$INIT" ]; then
    #As the last resort
    echo "Warning: setting init to /bin/sh"
    INIT="/bin/sh"
fi

[ -f "/tmp/item_VARS" ] && . /tmp/item_VARS

#unmount everything
umount -r /dev
umount -r /sys
umount -r /proc

echo "Good Bye!"

exec switch_root /mnt "$INIT"
